# Конфигурация источников данных Grafana
# Автоматическая настройка источника данных Prometheus

apiVersion: 1

datasources:
  # Основной источник данных Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://ntrip-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:
        # Интеграция трассировки (опционально)
        - name: trace_id
          datasourceUid: jaeger
    uid: prometheus
    version: 1
  
  # Опционально: если есть другие экземпляры Prometheus
  # - name: Prometheus-External
  #   type: prometheus
  #   access: proxy
  #   url: https://external-prometheus.example.com
  #   isDefault: false
  #   editable: true
  #   basicAuth: true
  #   basicAuthUser: username
  #   secureJsonData:
  #     basicAuthPassword: password
  #   jsonData:
  #     httpMethod: POST
  #     manageAlerts: false
  #     prometheusType: Prometheus
  #   uid: prometheus-external
  #   version: 1
  
  # Опционально: источник данных логов Loki
  # - name: Loki
  #   type: loki
  #   access: proxy
  #   url: http://loki:3100
  #   isDefault: false
  #   editable: true
  #   jsonData:
  #     maxLines: 1000
  #     derivedFields:
  #       - datasourceUid: jaeger
  #         matcherRegex: "trace_id=(\\w+)"
  #         name: TraceID
  #         url: "$${__value.raw}"
  #   uid: loki
  #   version: 1
  
  # Опционально: источник данных трассировки Jaeger
  # - name: Jaeger
  #   type: jaeger
  #   access: proxy
  #   url: http://jaeger:16686
  #   isDefault: false
  #   editable: true
  #   jsonData:
  #     tracesToLogs:
  #       datasourceUid: loki
  #       tags: ['job', 'instance', 'pod', 'namespace']
  #       mappedTags: [{ key: 'service.name', value: 'service' }]
  #       mapTagNamesEnabled: false
  #       spanStartTimeShift: '1h'
  #       spanEndTimeShift: '1h'
  #       filterByTraceID: false
  #       filterBySpanID: false
  #   uid: jaeger
  #   version: 1
  
  # Опционально: источник данных TestData (для тестирования)
  - name: TestData
    type: testdata
    access: proxy
    isDefault: false
    editable: true
    uid: testdata
    version: 1